import { EmailMode } from '@/platform/config/constants/email.constants';
import { EnvVar, NodeEnvironment } from '@/platform/config/constants/env.constants';
import { LangfuseMode } from '@/platform/config/constants/langfuse.constants';
import { LogLevel } from '@/platform/config/constants/log-level.constants';

export const TEST_ENV: Readonly<Record<EnvVar, string>> = {
  [EnvVar.NodeEnv]: NodeEnvironment.Test,
  [EnvVar.AppVersion]: '0.0.0-test',
  [EnvVar.LogLevel]: LogLevel.Silent,
  [EnvVar.HttpHost]: '127.0.0.1',
  [EnvVar.ApiPort]: '3000',
  [EnvVar.GatewayPort]: '3001',
  [EnvVar.WorkerPort]: '3002',
  [EnvVar.DatabaseUrl]: 'postgres://app:app@localhost:5432/agent_ic',
  [EnvVar.DatabaseSystemUrl]: 'postgres://app_system:app_system@localhost:5432/agent_ic',
  [EnvVar.DatabaseOwnerUrl]: 'postgres://app_owner:app_owner@localhost:5432/agent_ic',
  [EnvVar.DatabasePoolMax]: '2',
  [EnvVar.RedisQueueUrl]: 'redis://localhost:6379/0',
  [EnvVar.RedisCacheUrl]: 'redis://localhost:6379/0',
  [EnvVar.WorkerConcurrency]: '2',
  [EnvVar.PlatformAdminDevAccess]: 'false',
  [EnvVar.OtelSdkDisabled]: 'true',
  [EnvVar.OtelExporterEndpoint]: 'http://localhost:4318',
  [EnvVar.OtelServiceName]: 'test-service',
  [EnvVar.OtelServiceNamespace]: 'test-namespace',
  [EnvVar.LangfuseMode]: LangfuseMode.Off,
  [EnvVar.LangfuseSampleRate]: '1',
  [EnvVar.LangfuseHost]: 'http://localhost:3000',
  [EnvVar.LangfusePublicKey]: 'test-public-key',
  [EnvVar.LangfuseSecretKey]: 'test-secret-key',
  [EnvVar.PublicUrl]: 'https://app.agent-ic.test',
  [EnvVar.JwtAccessSecret]: 'test-access-secret-0123456789abcdef0123456789',
  [EnvVar.InviteTokenSecret]: 'test-invite-secret-0123456789abcdef0123456789',
  [EnvVar.SecretBoxKey]: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  [EnvVar.SecretBoxKeyVersion]: '1',
  [EnvVar.SecretBoxPreviousKeys]: '',
  [EnvVar.LlmBaseUrl]: 'http://127.0.0.1:4010/v1',
  [EnvVar.LlmApiKey]: '',
  [EnvVar.EmbeddingModel]: 'test-embedding-model',
  [EnvVar.EmailMode]: EmailMode.Smtp,
  [EnvVar.EmailFrom]: 'agent-ic <no-reply@agent-ic.test>',
  [EnvVar.SmtpHost]: '127.0.0.1',
  [EnvVar.SmtpPort]: '1025',
  [EnvVar.SmtpSecure]: 'false',
  [EnvVar.SmtpRequireTls]: 'false',
  [EnvVar.SmtpUser]: '',
  [EnvVar.SmtpPassword]: '',
  [EnvVar.ResendApiKey]: 'test-resend-key',
};

export const TEST_ARGV_PREFIX: readonly string[] = ['node', 'main'];
