packages:
  - apps/*
  - packages/*
allowBuilds:
  '@swc/core': false
  cpu-features: false
  esbuild: true
  lefthook: false
  protobufjs: false
  ssh2: false
packageExtensions:
  dependency-cruiser:
    dependencies:
      typescript: ^6
