import {
  LlmAgentFinish,
  LlmApi,
  LlmModelId,
  LlmPurpose,
  LlmReasoningEffort,
  LlmStructuredOutput,
  LlmVendor,
} from '@/platform/llm/constants/llm-model.constants';
import type { LlmModel } from '@/platform/llm/typedefs/llm-model.typedefs';

export const LLM_CATALOG: Readonly<Record<LlmModelId, LlmModel>> = {
  [LlmModelId.Gpt6Luna]: {
    id: LlmModelId.Gpt6Luna,
    vendor: LlmVendor.OpenAi,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.ClaudeHaiku55,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [
      LlmReasoningEffort.None,
      LlmReasoningEffort.Low,
      LlmReasoningEffort.Medium,
      LlmReasoningEffort.High,
      LlmReasoningEffort.XHigh,
    ],
    reasoningEffort: LlmReasoningEffort.None,
    reasoningWithTools: LlmReasoningEffort.None,
  },
  [LlmModelId.Ministral14b]: {
    id: LlmModelId.Ministral14b,
    vendor: LlmVendor.Mistral,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.2, outputUsdPerMillionTokens: 0.2 },
    fallback: LlmModelId.Gemma4,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [],
    reasoningEffort: null,
    reasoningWithTools: null,
  },
  [LlmModelId.ClaudeHaiku55]: {
    id: LlmModelId.ClaudeHaiku55,
    vendor: LlmVendor.Anthropic,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Gpt6Luna,
    api: LlmApi.AnthropicMessages,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [
      LlmReasoningEffort.Low,
      LlmReasoningEffort.Medium,
      LlmReasoningEffort.High,
      LlmReasoningEffort.XHigh,
      LlmReasoningEffort.Max,
    ],
    reasoningEffort: LlmReasoningEffort.Low,
    reasoningWithTools: null,
  },
  [LlmModelId.MimoV26Flash]: {
    id: LlmModelId.MimoV26Flash,
    vendor: LlmVendor.Xiaomi,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.14, outputUsdPerMillionTokens: 0.28 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [LlmReasoningEffort.Low, LlmReasoningEffort.Medium, LlmReasoningEffort.High],
    reasoningEffort: LlmReasoningEffort.Low,
    reasoningWithTools: null,
  },
  [LlmModelId.Gemma4]: {
    id: LlmModelId.Gemma4,
    vendor: LlmVendor.Google,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.13, outputUsdPerMillionTokens: 0.4 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [],
    reasoningEffort: null,
    reasoningWithTools: null,
  },
  [LlmModelId.Glm53Flash]: {
    id: LlmModelId.Glm53Flash,
    vendor: LlmVendor.Zhipu,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.15, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [LlmReasoningEffort.Low, LlmReasoningEffort.High, LlmReasoningEffort.Max],
    reasoningEffort: LlmReasoningEffort.Low,
    reasoningWithTools: null,
  },
  [LlmModelId.DeepSeekV41Flash]: {
    id: LlmModelId.DeepSeekV41Flash,
    vendor: LlmVendor.DeepSeek,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.3, outputUsdPerMillionTokens: 1.2 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [
      LlmReasoningEffort.Low,
      LlmReasoningEffort.Medium,
      LlmReasoningEffort.High,
      LlmReasoningEffort.XHigh,
      LlmReasoningEffort.Max,
    ],
    reasoningEffort: null,
    reasoningWithTools: null,
  },
};

export const LLM_DEFAULT_MODEL: Readonly<Record<LlmPurpose, LlmModelId>> = {
  [LlmPurpose.Conversation]: LlmModelId.Gpt6Luna,
  [LlmPurpose.Light]: LlmModelId.Gpt6Luna,
};
