import {
  LlmAgentFinish,
  LlmApi,
  LlmModelId,
  LlmPurpose,
  LlmReasoningEffort,
  LlmStructuredOutput,
  LlmVendor,
} from '@/platform/llm/constants/llm-model.constants';
import type { LlmModel } from '@/platform/llm/typedefs/llm-model.typedefs';

export const LLM_CATALOG: Readonly<Record<LlmModelId, LlmModel>> = {
  [LlmModelId.Gpt6Luna]: {
    id: LlmModelId.Gpt6Luna,
    vendor: LlmVendor.OpenAi,
    purpose: LlmPurpose.Conversation,
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.ClaudeHaiku55,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningEffort: LlmReasoningEffort.None,
  },
  [LlmModelId.Ministral14b]: {
    id: LlmModelId.Ministral14b,
    vendor: LlmVendor.Mistral,
    purpose: LlmPurpose.Light,
    price: { inputUsdPerMillionTokens: 0.2, outputUsdPerMillionTokens: 0.2 },
    fallback: LlmModelId.Gemma4,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningEffort: null,
  },
  [LlmModelId.ClaudeHaiku55]: {
    id: LlmModelId.ClaudeHaiku55,
    vendor: LlmVendor.Anthropic,
    purpose: LlmPurpose.Conversation,
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Gpt6Luna,
    api: LlmApi.AnthropicMessages,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningEffort: LlmReasoningEffort.Low,
  },
  [LlmModelId.MimoV26Flash]: {
    id: LlmModelId.MimoV26Flash,
    vendor: LlmVendor.Xiaomi,
    purpose: LlmPurpose.Conversation,
    price: { inputUsdPerMillionTokens: 0.14, outputUsdPerMillionTokens: 0.28 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningEffort: LlmReasoningEffort.Low,
  },
  [LlmModelId.Gemma4]: {
    id: LlmModelId.Gemma4,
    vendor: LlmVendor.Google,
    purpose: LlmPurpose.Light,
    price: { inputUsdPerMillionTokens: 0.13, outputUsdPerMillionTokens: 0.4 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningEffort: null,
  },
  [LlmModelId.Glm53Flash]: {
    id: LlmModelId.Glm53Flash,
    vendor: LlmVendor.Zhipu,
    purpose: LlmPurpose.Conversation,
    price: { inputUsdPerMillionTokens: 0.15, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningEffort: LlmReasoningEffort.Low,
  },
  [LlmModelId.DeepSeekV41Flash]: {
    id: LlmModelId.DeepSeekV41Flash,
    vendor: LlmVendor.DeepSeek,
    purpose: LlmPurpose.Conversation,
    price: { inputUsdPerMillionTokens: 0.3, outputUsdPerMillionTokens: 1.2 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningEffort: null,
  },
  [LlmModelId.Qwen35_9b]: {
    id: LlmModelId.Qwen35_9b,
    vendor: LlmVendor.Alibaba,
    purpose: LlmPurpose.Light,
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.15 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningEffort: null,
  },
};

export const LLM_DEFAULT_MODEL: Readonly<Record<LlmPurpose, LlmModelId>> = {
  [LlmPurpose.Conversation]: LlmModelId.MimoV26Flash,
  [LlmPurpose.Light]: LlmModelId.Ministral14b,
};
