import { ReasoningLevel } from '@agent-ic/contracts';
import {
  EmbeddingModelId,
  LlmAgentFinish,
  LlmApi,
  LlmModelId,
  LlmPurpose,
  LlmStructuredOutput,
  LlmVendor,
} from '@/platform/llm/constants/llm-model.constants';
import type { LlmEmbeddingModel, LlmModel } from '@/platform/llm/typedefs/llm-model.typedefs';

export const LLM_CATALOG: Readonly<Record<LlmModelId, LlmModel>> = {
  [LlmModelId.Gpt6Luna]: {
    id: LlmModelId.Gpt6Luna,
    vendor: LlmVendor.OpenAi,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.ClaudeHaiku55,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [
      ReasoningLevel.None,
      ReasoningLevel.Low,
      ReasoningLevel.Medium,
      ReasoningLevel.High,
      ReasoningLevel.XHigh,
    ],
    reasoningEffort: ReasoningLevel.None,
  },
  [LlmModelId.Ministral14b]: {
    id: LlmModelId.Ministral14b,
    vendor: LlmVendor.Mistral,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.2, outputUsdPerMillionTokens: 0.2 },
    fallback: LlmModelId.Gemma4,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [],
    reasoningEffort: null,
  },
  [LlmModelId.ClaudeHaiku55]: {
    id: LlmModelId.ClaudeHaiku55,
    vendor: LlmVendor.Anthropic,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.1, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Gpt6Luna,
    api: LlmApi.AnthropicMessages,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.FinalMessage,
    reasoningLevels: [
      ReasoningLevel.Low,
      ReasoningLevel.Medium,
      ReasoningLevel.High,
      ReasoningLevel.XHigh,
      ReasoningLevel.Max,
    ],
    reasoningEffort: ReasoningLevel.Low,
  },
  [LlmModelId.MimoV26Flash]: {
    id: LlmModelId.MimoV26Flash,
    vendor: LlmVendor.Xiaomi,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.14, outputUsdPerMillionTokens: 0.28 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [ReasoningLevel.Low, ReasoningLevel.Medium, ReasoningLevel.High],
    reasoningEffort: ReasoningLevel.Low,
  },
  [LlmModelId.Gemma4]: {
    id: LlmModelId.Gemma4,
    vendor: LlmVendor.Google,
    purposes: [LlmPurpose.Conversation, LlmPurpose.Light],
    price: { inputUsdPerMillionTokens: 0.13, outputUsdPerMillionTokens: 0.4 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonSchema,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [],
    reasoningEffort: null,
  },
  [LlmModelId.Glm53Flash]: {
    id: LlmModelId.Glm53Flash,
    vendor: LlmVendor.Zhipu,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.15, outputUsdPerMillionTokens: 0.5 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [ReasoningLevel.Low, ReasoningLevel.High, ReasoningLevel.Max],
    reasoningEffort: ReasoningLevel.Low,
  },
  [LlmModelId.DeepSeekV41Flash]: {
    id: LlmModelId.DeepSeekV41Flash,
    vendor: LlmVendor.DeepSeek,
    purposes: [LlmPurpose.Conversation],
    price: { inputUsdPerMillionTokens: 0.3, outputUsdPerMillionTokens: 1.2 },
    fallback: LlmModelId.Ministral14b,
    api: LlmApi.ChatCompletions,
    structuredOutput: LlmStructuredOutput.JsonObject,
    agentFinish: LlmAgentFinish.ReplyTool,
    reasoningLevels: [
      ReasoningLevel.Low,
      ReasoningLevel.Medium,
      ReasoningLevel.High,
      ReasoningLevel.XHigh,
      ReasoningLevel.Max,
    ],
    reasoningEffort: null,
  },
};

export const LLM_DEFAULT_MODEL: Readonly<Record<LlmPurpose, LlmModelId>> = {
  [LlmPurpose.Conversation]: LlmModelId.Gpt6Luna,
  [LlmPurpose.Light]: LlmModelId.Gpt6Luna,
};

export const EMBEDDING_CATALOG: Readonly<Record<EmbeddingModelId, LlmEmbeddingModel>> = {
  [EmbeddingModelId.JinaEmbeddingsV5TextSmall]: {
    id: EmbeddingModelId.JinaEmbeddingsV5TextSmall,
    vendor: LlmVendor.Jina,
    price: { inputUsdPerMillionTokens: 0.02, outputUsdPerMillionTokens: 0 },
    dimensions: 1024,
    batchSize: 128,
  },
};
