export const DOMAIN_EVENT_SUBSCRIPTIONS = Symbol('DOMAIN_EVENT_SUBSCRIPTIONS');
export const DOMAIN_EVENT_LISTENER_SUBSCRIPTION = Symbol('DOMAIN_EVENT_LISTENER_SUBSCRIPTION');
export const MISSING_DOMAIN_EVENT_SUBSCRIPTION_MESSAGE =
  'listener is not decorated with @OnDomainEvent:';
export const SUBSCRIPTION_EVENT_FIELD = 'event';
