extend type Query {
  me: User!
}

type Mutation {
  resendConfirmation(input: ResendConfirmationInput!): ResendConfirmationPayload!
  forgotPassword(input: ForgotPasswordInput!): ForgotPasswordPayload!
  updateMyLocale(input: UpdateMyLocaleInput!): User!
}

enum Locale {
  en
  uk
}

type User {
  id: ID!
  email: String!
  name: String!
  locale: Locale!
}

input ResendConfirmationInput {
  email: String
  token: String
}

type ResendConfirmationPayload {
  accepted: Boolean!
}

input ForgotPasswordInput {
  email: String!
}

type ForgotPasswordPayload {
  accepted: Boolean!
}

input UpdateMyLocaleInput {
  locale: Locale!
}
