export enum FlowIssueSeverity {
  Error = 'error',
  Warning = 'warning',
}

export enum FlowIssueCode {
  UnsupportedVersion = 'UNSUPPORTED_VERSION',
  InvalidDocument = 'INVALID_DOCUMENT',
  DuplicateNodeId = 'DUPLICATE_NODE_ID',
  DuplicateNodeKey = 'DUPLICATE_NODE_KEY',
  InvalidNodeKey = 'INVALID_NODE_KEY',
  ReservedNodeKey = 'RESERVED_NODE_KEY',
  DuplicateEdgeId = 'DUPLICATE_EDGE_ID',
  EdgeMissingNode = 'EDGE_MISSING_NODE',
  EdgeMissingPort = 'EDGE_MISSING_PORT',
  EdgeIntoTrigger = 'EDGE_INTO_TRIGGER',
  PortHasManyEdges = 'PORT_HAS_MANY_EDGES',
  NoTrigger = 'NO_TRIGGER',
  Cycle = 'CYCLE',
  UnreachableNode = 'UNREACHABLE_NODE',
  UnknownVariable = 'UNKNOWN_VARIABLE',
  InvalidTemplate = 'INVALID_TEMPLATE',
  OperatorTypeMismatch = 'OPERATOR_TYPE_MISMATCH',
  InvalidConditionValue = 'INVALID_CONDITION_VALUE',
  VariableTypeMismatch = 'VARIABLE_TYPE_MISMATCH',
  MissingPrompt = 'MISSING_PROMPT',
  MissingModel = 'MISSING_MODEL',
  MissingEventName = 'MISSING_EVENT_NAME',
  MissingChannel = 'MISSING_CHANNEL',
  RuleWithoutConditions = 'RULE_WITHOUT_CONDITIONS',
  DuplicateRuleId = 'DUPLICATE_RULE_ID',
  InvalidRuleId = 'INVALID_RULE_ID',
  ParallelBranchLeak = 'PARALLEL_BRANCH_LEAK',
  SendInParallelBranch = 'SEND_IN_PARALLEL_BRANCH',
  TooFewBranches = 'TOO_FEW_BRANCHES',
  TooManyBranches = 'TOO_MANY_BRANCHES',
  ObserverHasEdges = 'OBSERVER_HAS_EDGES',
  ErrorPortNotConnected = 'ERROR_PORT_NOT_CONNECTED',
  DuplicateEventName = 'DUPLICATE_EVENT_NAME',
  InvalidCron = 'INVALID_CRON',
  InvalidTimeZone = 'INVALID_TIME_ZONE',
  DuplicateOutputField = 'DUPLICATE_OUTPUT_FIELD',
  PortNotConnected = 'PORT_NOT_CONNECTED',
  NoErrorPath = 'NO_ERROR_PATH',
  WaitForResultWithoutReply = 'WAIT_FOR_RESULT_WITHOUT_REPLY',
  NoFallbackMessage = 'NO_FALLBACK_MESSAGE',
}

export const WARNING_CODES: readonly FlowIssueCode[] = [
  FlowIssueCode.PortNotConnected,
  FlowIssueCode.NoErrorPath,
  FlowIssueCode.WaitForResultWithoutReply,
  FlowIssueCode.NoFallbackMessage,
];
