export const WORKSPACE_SWITCHER_LOGO_ICON_SIZE = 15;
export const WORKSPACE_SWITCHER_LOGO_STROKE_WIDTH = 1.8;
export const WORKSPACE_SWITCHER_CHEVRON_SIZE = 12;
export const WORKSPACE_SWITCHER_DETAIL_SEPARATOR = ' · ';
export const WORKSPACE_SWITCHER_INITIALS_LIMIT = 2;
export const WORKSPACE_SWITCHER_WORD_PATTERN = /\s+/;
