export { WorkspaceSection } from '@/features/workspace/constants/navigation.constants';
export { SectionGate } from '@/features/workspace/containers/SectionGate';
export { SectionPlaceholderPage } from '@/features/workspace/containers/SectionPlaceholderPage';
export { WorkspaceAccess } from '@/features/workspace/containers/WorkspaceAccess';
export { WorkspaceHome } from '@/features/workspace/containers/WorkspaceHome';
export { WorkspaceNavigation } from '@/features/workspace/containers/WorkspaceNavigation';
export { useActiveWorkspace } from '@/features/workspace/communication/hooks/useActiveWorkspace';
export { canOpenSection } from '@/features/workspace/logic/helpers/navigation.helpers';
export type { WorkspaceSummary } from '@/features/workspace/typedefs/workspace.typedefs';
export { useUpdateMyLocale } from '@/features/workspace/communication/hooks/useUpdateMyLocale';
