export enum ErrorCode {
  NotFound = 'NOT_FOUND',
  Forbidden = 'FORBIDDEN',
  Unauthenticated = 'UNAUTHENTICATED',
  Conflict = 'CONFLICT',
  PreconditionFailed = 'PRECONDITION_FAILED',
  BadUserInput = 'BAD_USER_INPUT',
  LimitReached = 'LIMIT_REACHED',
  UpstreamError = 'UPSTREAM_ERROR',
  Internal = 'INTERNAL',
}

export enum ErrorReason {
  Internal = 'INTERNAL',
  UpstreamFailed = 'UPSTREAM_FAILED',
  InvalidRequest = 'INVALID_REQUEST',
  RouteNotFound = 'ROUTE_NOT_FOUND',
  InvalidAccessToken = 'INVALID_ACCESS_TOKEN',
  InvalidId = 'INVALID_ID',
  InvalidCursor = 'INVALID_CURSOR',
  InvalidPageSize = 'INVALID_PAGE_SIZE',
  RateLimited = 'RATE_LIMITED',
  PlatformAdminRequired = 'PLATFORM_ADMIN_REQUIRED',
  AuthenticationRequired = 'AUTHENTICATION_REQUIRED',
  SystemActorRequired = 'SYSTEM_ACTOR_REQUIRED',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  EmailNotConfirmed = 'EMAIL_NOT_CONFIRMED',
  EmailTaken = 'EMAIL_TAKEN',
  InvalidEmail = 'INVALID_EMAIL',
  InvalidName = 'INVALID_NAME',
  PasswordTooShort = 'PASSWORD_TOO_SHORT',
  PasswordTooLong = 'PASSWORD_TOO_LONG',
  InvalidRefreshToken = 'INVALID_REFRESH_TOKEN',
  TokenInvalid = 'TOKEN_INVALID',
  TokenExpired = 'TOKEN_EXPIRED',
}
