export enum ErrorCode {
  NotFound = 'NOT_FOUND',
  Forbidden = 'FORBIDDEN',
  Unauthenticated = 'UNAUTHENTICATED',
  Conflict = 'CONFLICT',
  PreconditionFailed = 'PRECONDITION_FAILED',
  BadUserInput = 'BAD_USER_INPUT',
  LimitReached = 'LIMIT_REACHED',
  UpstreamError = 'UPSTREAM_ERROR',
  Internal = 'INTERNAL',
}

export enum ErrorReason {
  Internal = 'INTERNAL',
  UpstreamFailed = 'UPSTREAM_FAILED',
  InvalidRequest = 'INVALID_REQUEST',
  RouteNotFound = 'ROUTE_NOT_FOUND',
  InvalidAccessToken = 'INVALID_ACCESS_TOKEN',
  InvalidId = 'INVALID_ID',
  InvalidCursor = 'INVALID_CURSOR',
  InvalidPageSize = 'INVALID_PAGE_SIZE',
  RateLimited = 'RATE_LIMITED',
  PlatformAdminRequired = 'PLATFORM_ADMIN_REQUIRED',
  AuthenticationRequired = 'AUTHENTICATION_REQUIRED',
  SystemActorRequired = 'SYSTEM_ACTOR_REQUIRED',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  EmailNotConfirmed = 'EMAIL_NOT_CONFIRMED',
  EmailTaken = 'EMAIL_TAKEN',
  InvalidEmail = 'INVALID_EMAIL',
  InvalidName = 'INVALID_NAME',
  PasswordTooShort = 'PASSWORD_TOO_SHORT',
  PasswordTooLong = 'PASSWORD_TOO_LONG',
  InvalidRefreshToken = 'INVALID_REFRESH_TOKEN',
  TokenInvalid = 'TOKEN_INVALID',
  TokenExpired = 'TOKEN_EXPIRED',
  EmailAlreadyConfirmed = 'EMAIL_ALREADY_CONFIRMED',
  ConfirmationBrowserMismatch = 'CONFIRMATION_BROWSER_MISMATCH',
  CrossOriginRequest = 'CROSS_ORIGIN_REQUEST',
  UnsupportedContentType = 'UNSUPPORTED_CONTENT_TYPE',
  WorkspaceAccessDenied = 'WORKSPACE_ACCESS_DENIED',
  PermissionDenied = 'PERMISSION_DENIED',
  InviteInvalid = 'INVITE_INVALID',
  InviteExpired = 'INVITE_EXPIRED',
  InvalidWorkspaceName = 'INVALID_WORKSPACE_NAME',
  InvalidTimeZone = 'INVALID_TIME_ZONE',
  RoleNotInvitable = 'ROLE_NOT_INVITABLE',
  SecretKeyVersionUnknown = 'SECRET_KEY_VERSION_UNKNOWN',
  SecretTampered = 'SECRET_TAMPERED',
}
