ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO app, app_system;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app, app_system;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES GRANT USAGE, SELECT ON SEQUENCES TO app, app_system;
